/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<
      'Home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '404': RouteRecordInfo<
      '404',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    'Charts': RouteRecordInfo<
      'Charts',
      '/charts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Counter': RouteRecordInfo<
      'Counter',
      '/counter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ForgotPassword': RouteRecordInfo<
      'ForgotPassword',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'KeepAlive': RouteRecordInfo<
      'KeepAlive',
      '/keepalive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Login': RouteRecordInfo<
      'Login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Mock': RouteRecordInfo<
      'Mock',
      '/mock',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Profile': RouteRecordInfo<
      'Profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Register': RouteRecordInfo<
      'Register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ScrollCache': RouteRecordInfo<
      'ScrollCache',
      '/scroll-cache',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Settings': RouteRecordInfo<
      'Settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'UnoCSS': RouteRecordInfo<
      'UnoCSS',
      '/unocss',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'WmsHome': RouteRecordInfo<
      'WmsHome',
      '/wms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'WmsInbound': RouteRecordInfo<
      'WmsInbound',
      '/wms/inbound',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'WmsInboundDetail': RouteRecordInfo<
      'WmsInboundDetail',
      '/wms/inbound/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'WmsInboundCreate': RouteRecordInfo<
      'WmsInboundCreate',
      '/wms/inbound/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'WmsLookup': RouteRecordInfo<
      'WmsLookup',
      '/wms/lookup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'WmsOutbound': RouteRecordInfo<
      'WmsOutbound',
      '/wms/outbound',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'WmsOutboundDetail': RouteRecordInfo<
      'WmsOutboundDetail',
      '/wms/outbound/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'WmsOutboundCreate': RouteRecordInfo<
      'WmsOutboundCreate',
      '/wms/outbound/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'Home'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '404'
      views:
        | never
    }
    'src/pages/charts/index.vue': {
      routes:
        | 'Charts'
      views:
        | never
    }
    'src/pages/counter/index.vue': {
      routes:
        | 'Counter'
      views:
        | never
    }
    'src/pages/forgot-password/index.vue': {
      routes:
        | 'ForgotPassword'
      views:
        | never
    }
    'src/pages/keepalive/index.vue': {
      routes:
        | 'KeepAlive'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | 'Login'
      views:
        | never
    }
    'src/pages/mock/index.vue': {
      routes:
        | 'Mock'
      views:
        | never
    }
    'src/pages/profile/index.vue': {
      routes:
        | 'Profile'
      views:
        | never
    }
    'src/pages/register/index.vue': {
      routes:
        | 'Register'
      views:
        | never
    }
    'src/pages/scroll-cache/index.vue': {
      routes:
        | 'ScrollCache'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | 'Settings'
      views:
        | never
    }
    'src/pages/unocss/index.vue': {
      routes:
        | 'UnoCSS'
      views:
        | never
    }
    'src/pages/wms/index.vue': {
      routes:
        | 'WmsHome'
      views:
        | never
    }
    'src/pages/wms/inbound/index.vue': {
      routes:
        | 'WmsInbound'
      views:
        | never
    }
    'src/pages/wms/inbound/[id].vue': {
      routes:
        | 'WmsInboundDetail'
      views:
        | never
    }
    'src/pages/wms/inbound/create.vue': {
      routes:
        | 'WmsInboundCreate'
      views:
        | never
    }
    'src/pages/wms/lookup/index.vue': {
      routes:
        | 'WmsLookup'
      views:
        | never
    }
    'src/pages/wms/outbound/index.vue': {
      routes:
        | 'WmsOutbound'
      views:
        | never
    }
    'src/pages/wms/outbound/[id].vue': {
      routes:
        | 'WmsOutboundDetail'
      views:
        | never
    }
    'src/pages/wms/outbound/create.vue': {
      routes:
        | 'WmsOutboundCreate'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
